/* EMERALD — content database
   Every page on the site is generated from this file. Run `node build.js` after editing. */

const neighborhoods = [
  {
    slug: "pike-place-waterfront",
    num: "01",
    name: "Pike Place & Waterfront",
    shortName: "Pike Place",
    teaser: "Yes, it's the famous one — and it earns it. The market before 9 AM, the new Overlook Walk, and the gum wall, exactly as gross as promised.",
    metaDesc: "A field guide to Pike Place Market and Seattle's rebuilt waterfront: when to go, what to eat, the Overlook Walk, and the stops locals actually make.",
    lede: `The oldest continuously operating farmers market in America, hanging off a cliff over Elliott Bay. Nine acres, five levels, and — if you time it right — the best two hours of your trip.`,
    body: [
      `The move is simple: arrive before 9 AM on a weekday. You'll watch vendors build their flower stacks, hear the first salmon hit the scale at Pike Place Fish, and have Post Alley to yourself. By 11 AM on a Saturday the main arcade is a slow-motion crowd crush, and everything charming about the place gets harder to see.`,
      `Since 2024 the market connects straight down to the water via the Overlook Walk — a stair-stepped park that finally stitched the city to its own waterfront. Descend past the Aquarium's Ocean Pavilion to the rebuilt piers, then work your way back up through the market's lower levels: used books, vintage posters, a magic shop, and Rachel the bronze pig collecting donations since 1986.`,
    ],
    essentials: {
      getThere: "Link light rail to Westlake, 6-minute walk downhill",
      time: "2–4 hours",
      best: "Weekdays before 9 AM",
      pairs: { label: "Queen Anne & Seattle Center", href: "/neighborhoods/queen-anne-seattle-center/" },
    },
    map: { center: [47.6087, -122.3418], zoom: 16 },
    stops: [
      { name: "Pike Place Market", tag: "The main event", blurb: "Start at the fish throwers under the clock, then drift north through the produce and flower rows. The craft stalls rotate daily — no two visits match.", address: "85 Pike St", coords: [47.6089, -122.3407] },
      { name: "Storyville Coffee", tag: "Coffee with a view", blurb: "Upstairs in the Corner Market building, looking straight down Pike at the market sign. The city's best people-watching perch.", address: "94 Pike St, Suite 34", coords: [47.6089, -122.3401] },
      { name: "Overlook Walk", tag: "The new classic", blurb: "The stair-park connecting the market to the waterfront. Elliott Bay, ferries, and the Olympics stacked in front of you the whole way down.", address: "Pike St & Western Ave", coords: [47.6081, -122.3432] },
      { name: "Gum Wall", tag: "Regrettable, mandatory", blurb: "Down Post Alley under the market. Thousands of pieces of chewed gum on brick. You will take a photo. You will feel complicated about it.", address: "1428 Post Alley", coords: [47.6084, -122.3403] },
      { name: "Pike Place Chowder", tag: "The queue that's worth it", blurb: "Smoked salmon chowder in a bread bowl, eaten standing up. Go at an off-hour or order ahead; the line at noon is a tourist trap of your own making.", address: "1530 Post Alley", coords: [47.6096, -122.3417] },
      { name: "Sushi Kashiba", tag: "Book-ahead splurge", blurb: "Shiro Kashiba trained under Jiro before bringing edomae sushi to Seattle in 1966. Omakase at the bar if you can get it; book weeks out.", address: "86 Pine St, Suite 1", coords: [47.6100, -122.3408] },
    ],
    tip: "The producers' and craft stalls rotate daily, so the market is literally a different market every visit. And say yes to samples — it's how the vendors want you to shop.",
  },
  {
    slug: "capitol-hill",
    num: "02",
    name: "Capitol Hill",
    shortName: "Capitol Hill",
    teaser: "The city's loudest heartbeat: record stores, dive bars, the best restaurant row in the Northwest, and a glass conservatory glowing at golden hour.",
    metaDesc: "Capitol Hill, Seattle field guide: where to eat on the Pike/Pine corridor, Volunteer Park and its conservatory, record stores, cocktail bars, and live music.",
    lede: `Seattle's densest, loudest, most caffeinated neighborhood — where the restaurant openings happen, the shows go late, and the sidewalks stay busy after the rest of the city has gone home.`,
    body: [
      `Orient yourself on the Pike/Pine corridor: a dozen blocks of restaurants, bars, and venues running east from downtown. This is where you eat dinner in Seattle. Reservations help, but the local move is walking in solo or as a pair and taking the bar seats — kitchens here treat the bar as the best table in the house.`,
      `North of the corridor the Hill goes leafy and residential until it crests at Volunteer Park: an Olmsted-designed park with a Victorian glass conservatory, a brutalist water tower you can climb for free views, and the Seattle Asian Art Museum in a 1933 art-deco jewel box. The walk up 15th Avenue takes you past the neighborhood's quieter cafés and bookshops.`,
    ],
    essentials: {
      getThere: "Link light rail to Capitol Hill station",
      time: "Evening into the night",
      best: "Dinner onward; Sunday mornings for cafés",
      pairs: { label: "Chinatown–International District", href: "/neighborhoods/chinatown-international-district/" },
    },
    map: { center: [47.6190, -122.3200], zoom: 14 },
    stops: [
      { name: "Espresso Vivace", tag: "The espresso benchmark", blurb: "David Schomer basically wrote the American manual on espresso here. Order a cappuccino, admire the rosetta, drink it at the sidewalk bar on Broadway.", address: "532 Broadway Ave E", coords: [47.6234, -122.3210] },
      { name: "Elliott Bay Book Company", tag: "The bookstore", blurb: "Cedar shelves, creaking floors, 150,000 titles, and a reading calendar that pulls every touring author through town. Budget an hour minimum.", address: "1521 10th Ave", coords: [47.6146, -122.3196] },
      { name: "Volunteer Park Conservatory", tag: "Golden-hour target", blurb: "A 1912 Victorian glasshouse of orchids, ferns, and cacti. Tiny entry fee, huge payoff when the light goes low. Climb the water tower across the lawn after.", address: "1400 E Galer St", coords: [47.6321, -122.3151] },
      { name: "Canon", tag: "The whiskey library", blurb: "One of the largest spirit collections in the western hemisphere and cocktails to match. Small room, no standing — go early or late.", address: "928 12th Ave", coords: [47.6114, -122.3168] },
      { name: "Neumos", tag: "The venue", blurb: "The Pike/Pine anchor for touring bands since the Moe's days. Check the calendar with Barboza downstairs — something's always on.", address: "925 E Pike St", coords: [47.6139, -122.3195] },
    ],
    tip: "Don't over-plan dinner. Pick the corridor, walk it once, and take bar seats wherever feels right — Capitol Hill kitchens save their best hospitality for walk-ins at the bar.",
  },
  {
    slug: "ballard",
    num: "03",
    name: "Ballard",
    shortName: "Ballard",
    teaser: "Old fishing village turned brewery capital. Salmon climbing the fish ladder, a Sunday market, and a dozen breweries in walking distance.",
    metaDesc: "Ballard, Seattle field guide: the Ballard Locks and fish ladder, Sunday farmers market, Ballard Avenue's bars and breweries, and the National Nordic Museum.",
    lede: `A Scandinavian fishing town that Seattle swallowed in 1907 and never fully digested. The fishing fleet still ties up here — it just shares the neighborhood with breweries now.`,
    body: [
      `Start at the Ballard Locks, the busiest in the nation: sailboats and salmon trawlers rising and falling between Puget Sound and the freshwater ship canal while tourists lean over the railings. The fish ladder's underwater viewing windows are the real show — sockeye and chinook muscling upstream all summer, herons and sea lions running interference.`,
      `Then it's a flat walk to Ballard Avenue, a National Historic District of 1890s brick that now holds the city's best concentration of bars, restaurants, and shops. Sundays add the year-round farmers market down the middle of the street. The surrounding blocks hide more than a dozen breweries — Reuben's, Stoup, Fair Isle — most of them kid-and-dog-tolerant taprooms a few minutes' walk apart.`,
    ],
    essentials: {
      getThere: "RapidRide D from downtown, about 25 minutes",
      time: "Half a day",
      best: "Sundays — market by day, Ballard Ave by night",
      pairs: { label: "Fremont, via the Burke-Gilman Trail", href: "/neighborhoods/fremont/" },
    },
    map: { center: [47.6663, -122.3870], zoom: 14 },
    stops: [
      { name: "Ballard Locks & Fish Ladder", tag: "Free and mesmerizing", blurb: "Officially the Hiram M. Chittenden Locks. Boats going up, salmon going upstream, gardens on the shore. Salmon peak late June through September.", address: "3015 NW 54th St", coords: [47.6655, -122.3976] },
      { name: "Ballard Farmers Market", tag: "Sundays, rain or shine", blurb: "Year-round, every Sunday, down the middle of Ballard Ave. Produce and flowers up front; the food stalls at the ends are lunch.", address: "Ballard Ave NW, 20th–22nd", coords: [47.6678, -122.3846] },
      { name: "The Walrus and the Carpenter", tag: "The oyster pilgrimage", blurb: "Renee Erickson's marble-countered oyster bar that put Ballard on the national food map. No reservations — arrive before doors at 4 PM or embrace the wait.", address: "4743 Ballard Ave NW", coords: [47.6656, -122.3820] },
      { name: "National Nordic Museum", tag: "The heritage stop", blurb: "A genuinely beautiful museum of the Nordic migration that built this neighborhood — fjord-like central hall, Viking-to-modern-design collection.", address: "2655 NW Market St", coords: [47.6685, -122.3937] },
      { name: "Tractor Tavern", tag: "Night cap with twang", blurb: "Ballard Ave's wood-floored, wagon-wheel-lit venue for Americana, folk, and whatever's rolling through. One of the best-sounding small rooms in the city.", address: "5213 Ballard Ave NW", coords: [47.6672, -122.3852] },
    ],
    tip: "The locks are free, open daily, and best around midday when boat traffic peaks. In salmon season, go to the fish-ladder windows first — everyone forgets them until they're leaving.",
  },
  {
    slug: "fremont",
    num: "04",
    name: "Fremont",
    shortName: "Fremont",
    teaser: "\"Center of the Universe,\" self-declared. A troll eats a Volkswagen under the bridge; a rocket is bolted to a shop. Seattle's weirdness, preserved.",
    metaDesc: "Fremont, Seattle field guide: the Fremont Troll, the rocket, the Lenin statue, Gas Works Park, Theo Chocolate, and the Sunday flea market.",
    lede: `A former counterculture enclave that declared itself the Center of the Universe, elected a troll as its landmark, and has been winking at the rest of the city ever since.`,
    body: [
      `Fremont is best done as a walking scavenger hunt: the Troll crushing a real VW Beetle under the Aurora Bridge, the 53-foot Cold War rocket bolted to a corner shop, the statue of Lenin that arrived from Slovakia in 1993 and has been controversial ever since, and 'Waiting for the Interurban' — cast-aluminum commuters that locals dress up for birthdays and protests.`,
      `Cap it at Gas Works Park, ten minutes east along the canal: a rusted 1906 gasification plant preserved as sculpture on a hill of grass, with the whole downtown skyline across Lake Union. Kite-flyers on the mound, seaplanes landing in front of you. On sunny evenings there is no better free seat in Seattle.`,
    ],
    essentials: {
      getThere: "Bus 62 or 40 from downtown; walkable from Ballard",
      time: "2–3 hours",
      best: "Sunday — flea market day",
      pairs: { label: "Ballard, one flat walk west", href: "/neighborhoods/ballard/" },
    },
    map: { center: [47.6495, -122.3440], zoom: 15 },
    stops: [
      { name: "Fremont Troll", tag: "The landmark", blurb: "Two tons of concrete under the Aurora Bridge, one real Volkswagen Beetle in its grip since 1990. Go early for a person-free photo.", address: "N 36th St at Troll Ave N", coords: [47.6510, -122.3473] },
      { name: "Fremont Rocket", tag: "Look up", blurb: "A 1950s military rocket fuselage bolted to the corner of a shop, complete with neon and the neighborhood motto: De Libertas Quirkas.", address: "601 N 35th St", coords: [47.6497, -122.3506] },
      { name: "Fremont Sunday Market", tag: "The flea", blurb: "Vintage, vinyl, street food, and genuine junk-drawer treasure, every Sunday since 1990. Runs year-round; peak sprawl in summer.", address: "3401 Evanston Ave N", coords: [47.6497, -122.3503] },
      { name: "Theo Chocolate", tag: "The factory stop", blurb: "Organic, fair-trade bean-to-bar pioneers. The factory store hands out generous samples; tours run most days if you want the full Wonka.", address: "3400 Phinney Ave N", coords: [47.6491, -122.3540] },
      { name: "Gas Works Park", tag: "The skyline seat", blurb: "Rusted industrial ruins, a kite hill, and the definitive Lake Union panorama. Sunset here with takeout is a complete Seattle evening.", address: "2101 N Northlake Way", coords: [47.6456, -122.3344] },
    ],
    tip: "Do Fremont on a Sunday and you can stack the flea market here with the Ballard Farmers Market — they're a 25-minute walk apart along the ship canal.",
  },
  {
    slug: "queen-anne-seattle-center",
    num: "05",
    name: "Queen Anne & Seattle Center",
    shortName: "Queen Anne",
    teaser: "The Space Needle, Chihuly's glass garden, MoPOP's melted-guitar building — then Kerry Park for the postcard view.",
    metaDesc: "Queen Anne and Seattle Center field guide: Space Needle strategy, Chihuly Garden and Glass, MoPOP, the Monorail, and the Kerry Park viewpoint.",
    lede: `The 1962 World's Fair grounds and the hill that looks down on them. Every Seattle icon in one compact campus — plus the city's most photographed viewpoint, ten minutes up the hill.`,
    body: [
      `Seattle Center is walkable in an afternoon: the Space Needle, Chihuly Garden and Glass next door, MoPOP's Frank Gehry-designed sheet-metal swirl, the International Fountain that kids treat as a water park, and the Monorail — the 1962 original — humming to Westlake every ten minutes. Contrarian but correct: if you only buy one ticket, make it Chihuly over the Needle. The glasshouse against the sky at dusk outclasses the elevator ride.`,
      `Then climb (or ride) up the south slope of Queen Anne Hill to Kerry Park. It's a sliver of a park with the definitive Seattle composition: Space Needle front and center, downtown stacked behind it, Elliott Bay to the right, and — on clear days — Rainier floating above the whole arrangement. Free, always open, best at golden hour.`,
    ],
    essentials: {
      getThere: "Monorail from Westlake, 2 minutes",
      time: "Half a day",
      best: "Golden hour at Kerry Park",
      pairs: { label: "Pike Place & Waterfront", href: "/neighborhoods/pike-place-waterfront/" },
    },
    map: { center: [47.6237, -122.3530], zoom: 15 },
    stops: [
      { name: "Space Needle", tag: "The icon", blurb: "605 feet, rebuilt interior with a rotating glass floor. Book the sunset slot in advance — walk-up daytime tickets mean queueing twice.", address: "400 Broad St", coords: [47.6205, -122.3493] },
      { name: "Chihuly Garden and Glass", tag: "The better ticket", blurb: "Dale Chihuly's glass in eight galleries and a garden where sculpture grows among real plants. The Glasshouse at dusk is the single best room in Seattle.", address: "305 Harrison St", coords: [47.6206, -122.3505] },
      { name: "MoPOP", tag: "Pop-culture church", blurb: "Museum of Pop Culture, in a Gehry building said to resemble a smashed guitar. Nirvana and Hendrix artifacts, sci-fi and horror galleries, a guitar tornado.", address: "325 5th Ave N", coords: [47.6215, -122.3481] },
      { name: "Seattle Center Monorail", tag: "Ride the future of 1962", blurb: "Ninety seconds of retro-futurism between Westlake and Seattle Center. ORCA cards work. Sit up front.", address: "Seattle Center Station, 370 Thomas St", coords: [47.6216, -122.3490] },
      { name: "Kerry Park", tag: "The postcard", blurb: "The definitive skyline viewpoint, 10 minutes up Queen Anne Ave. Needle, skyline, bay, and Rainier if she's out. Free, and better than most paid decks.", address: "211 W Highland Dr", coords: [47.6295, -122.3599] },
    ],
    tip: "Check whether the Mountain is out before committing to a paid observation deck. Overcast day? Do MoPOP and Chihuly instead and save the views — Kerry Park costs nothing whenever the sky clears.",
  },
  {
    slug: "chinatown-international-district",
    num: "06",
    name: "Chinatown–International District",
    shortName: "The C-ID",
    teaser: "Dim sum carts, the Wing Luke Museum, Uwajimaya's aisles of everything, and late-night hot pot in one of North America's oldest pan-Asian neighborhoods.",
    metaDesc: "Chinatown–International District, Seattle field guide: dim sum, Uwajimaya, the Wing Luke Museum, Little Saigon pho, and Hing Hay Park.",
    lede: `Chinatown, Japantown, and Little Saigon sharing a few dense blocks south of downtown — one of the oldest pan-Asian neighborhoods in North America, and pound for pound the best eating in the city.`,
    body: [
      `Come hungry and pace yourself. Weekend mornings mean dim sum — carts, dumplings, and controlled chaos at Jade Garden. Afternoons are for grazing: barbecue pork in the bakeries, banh mi in Little Saigon, and the full sensory sweep of Uwajimaya, the Asian superstore that's anchored the neighborhood since 1928. Evenings run late — hot pot, karaoke, and noodle shops that keep neighborhood hours, not tourist hours.`,
      `Between meals, the Wing Luke Museum tells the neighborhood's story better than any guide can — including the hard chapters, like the Japanese-American incarceration that emptied whole blocks here in 1942. It's a Smithsonian affiliate built into a 1910 hotel for immigrant workers, and its preserved-in-place hotel rooms upstairs will stay with you.`,
    ],
    essentials: {
      getThere: "Link light rail, one stop from Westlake",
      time: "3–4 hours, meals included",
      best: "Weekend mornings for dim sum",
      pairs: { label: "Capitol Hill, via the First Hill streetcar", href: "/neighborhoods/capitol-hill/" },
    },
    map: { center: [47.5981, -122.3220], zoom: 16 },
    stops: [
      { name: "Uwajimaya", tag: "The institution", blurb: "A city block of pan-Asian groceries, a food court, and the Kinokuniya bookstore. You will leave with snacks you didn't plan on. Correct.", address: "600 5th Ave S", coords: [47.5966, -122.3266] },
      { name: "Wing Luke Museum", tag: "The essential museum", blurb: "The Asian Pacific American experience, told inside a 1910 immigrant workers' hotel. Take the guided historic-hotel tour if the timing works.", address: "719 S King St", coords: [47.5983, -122.3220] },
      { name: "Jade Garden", tag: "Dim sum, cart-service", blurb: "Weekend dim sum the traditional way — flag the cart, point, eat. Shrimp dumplings and sticky rice in lotus leaf are the benchmarks. Cash is smart.", address: "424 7th Ave S", coords: [47.5989, -122.3238] },
      { name: "Phở Bắc Súp Shop", tag: "The pho standard", blurb: "The family that introduced pho to Seattle in 1982, now in a boat-shaped red building in Little Saigon. Rich broth, brisket, no shortcuts.", address: "1240 S Jackson St", coords: [47.5993, -122.3148] },
      { name: "Hing Hay Park", tag: "The neighborhood square", blurb: "Grand pagoda, ping-pong tables, tai chi in the mornings, and the best bench for eating whatever you just bought within a block of here.", address: "423 Maynard Ave S", coords: [47.5985, -122.3252] },
    ],
    tip: "Uwajimaya's food court is the neighborhood's most underrated lunch, and the grocery aisles are the best souvenir shop in Seattle — bring an empty tote.",
  },
  {
    slug: "west-seattle-alki",
    num: "07",
    name: "West Seattle & Alki",
    shortName: "West Seattle",
    teaser: "Take the water taxi across the bay — five minutes, best skyline view in town — to a beach neighborhood doing a convincing California impression.",
    metaDesc: "West Seattle and Alki Beach field guide: the King County Water Taxi, Alki Beach, Bakery Nouveau, and where Seattle was founded in 1851.",
    lede: `A peninsula that behaves like its own seaside town, reached by the best value in Seattle tourism: a water taxi across Elliott Bay with the skyline receding behind you.`,
    body: [
      `The crossing from Pier 50 takes about ten minutes and costs a few dollars on an ORCA card — it is, mile for mile, the best skyline viewing in the city, and locals treat it as a commute. From Seacrest dock, rent a bike or walk the shoreline path 2.5 miles around Duwamish Head to Alki Beach.`,
      `Alki is where the Denny Party landed in November 1851 and optimistically named the place 'New York Alki' — 'New York eventually' in Chinook jargon. Today it's Seattle's only real beach scene: volleyball courts, firepits, a miniature Statue of Liberty, and fish and chips eaten against a railing while the Olympics go pink across the Sound. Up the hill, the Junction is the neighborhood's main street, anchored by one of the best bakeries on the West Coast.`,
    ],
    essentials: {
      getThere: "King County Water Taxi from Pier 50",
      time: "Half a day",
      best: "Sunny afternoons into sunset",
      pairs: { label: "Downtown & Pike Place, one boat ride away", href: "/neighborhoods/pike-place-waterfront/" },
    },
    map: { center: [47.5830, -122.3990], zoom: 13 },
    stops: [
      { name: "King County Water Taxi", tag: "The crossing", blurb: "Pier 50 to Seacrest in about ten minutes, skyline the whole way. Check the sailing schedule — off-peak and winter service is thinner.", address: "Pier 50, 801 Alaskan Way", coords: [47.6019, -122.3374] },
      { name: "Marination Ma Kai", tag: "Dockside first stop", blurb: "Hawaiian-Korean at the Seacrest dock: kalbi tacos, spam sliders, shave ice, and a patio pointed straight at the skyline you just crossed.", address: "1660 Harbor Ave SW", coords: [47.5870, -122.3772] },
      { name: "Alki Beach", tag: "The beach", blurb: "2.5 miles of sand, volleyball, firepits, and promenade. The birthplace-of-Seattle monument and the tiny Statue of Liberty are both here.", address: "1702 Alki Ave SW", coords: [47.5812, -122.4088] },
      { name: "Bakery Nouveau", tag: "Worth the hill", blurb: "William Leaman took a U.S. team to the Coupe du Monde de la Boulangerie and then opened this. The twice-baked almond croissant has a citywide following.", address: "4737 California Ave SW", coords: [47.5609, -122.3868] },
    ],
    tip: "Ride over on the water taxi in daylight and time the return crossing for just after sunset — the skyline lights coming on over black water is the money shot of the whole trip.",
  },
  {
    slug: "georgetown",
    num: "08",
    name: "Georgetown",
    shortName: "Georgetown",
    teaser: "Industrial, muraled, gloriously unpolished. Art in old brewery buildings, hangar-sized antique malls, and planes roaring overhead.",
    metaDesc: "Georgetown, Seattle field guide: the arts district in old brewery buildings, Georgetown Trailer Park Mall, Fonda La Catrina, and second-Saturday Art Attack.",
    lede: `Seattle's oldest neighborhood and its least polished — a brick-and-corrugated-steel strip between the Duwamish River and Boeing Field where the city's working past never left, it just got murals.`,
    body: [
      `Georgetown runs on one walkable stretch of Airport Way South, lined with 1900s brewery buildings from the old Seattle Brewing & Malting Co. — once the biggest brewery west of the Mississippi. Today those brick halls hold artist studios, oddball shops, and some of the city's most reliable bars, all under a flight path that sends jets from Boeing Field low overhead. It's loud. It suits the place.`,
      `Come on the second Saturday of the month if you can, when the Georgetown Art Attack opens studios and galleries down the whole strip. Any other day, the routine is: browse the vintage trailers-turned-shops, dig through the antique mall, eat exceptional tacos in a Day-of-the-Dead courtyard, and settle into a century-old saloon while the planes rattle the glassware.`,
    ],
    essentials: {
      getThere: "Bus 124 from downtown, about 15 minutes",
      time: "2–3 hours",
      best: "Second Saturdays — Art Attack night",
      pairs: { label: "Chinatown–International District", href: "/neighborhoods/chinatown-international-district/" },
    },
    map: { center: [47.5478, -122.3215], zoom: 16 },
    stops: [
      { name: "Georgetown Trailer Park Mall", tag: "Shops in trailers", blurb: "Vintage travel trailers converted into micro-shops — records, oddities, mid-century whatnot. Weekend hours; peak Georgetown energy.", address: "5805 Airport Way S", coords: [47.5476, -122.3216] },
      { name: "Fonda La Catrina", tag: "The taco anchor", blurb: "Day of the Dead décor, handmade tortillas, and a courtyard that fills the second the sun appears. The carnitas are the order.", address: "5905 Airport Way S", coords: [47.5468, -122.3211] },
      { name: "Jules Maes Saloon", tag: "Drinking since 1888", blurb: "One of Seattle's oldest bars, pouring through the eras with shuffleboard, pinball, and zero pretension. The right last stop.", address: "5919 Airport Way S", coords: [47.5466, -122.3209] },
      { name: "Georgetown Art Attack", tag: "Second Saturdays", blurb: "The whole strip opens up — studios, galleries, pop-ups, live music — from early evening. The best single night to see the neighborhood.", address: "Airport Way S corridor", coords: [47.5480, -122.3218] },
    ],
    tip: "Georgetown rewards the unhurried. Pick an afternoon, not an hour — the point is the wander between the murals, not any single stop.",
  },
];

const eatCategories = [
  {
    slug: "coffee",
    cat: "COFFEE",
    name: "Coffee, taken seriously",
    teaser: "Skip the first-Starbucks line. Where locals actually queue, and how to order like you've done this before.",
    metaDesc: "Where to drink coffee in Seattle like a local: Espresso Vivace, Monorail Espresso, Victrola, and the etiquette that goes with them.",
    lede: `Seattle didn't invent coffee; it invented taking coffee personally. The espresso here has house styles, lineages, and grudges. Here's where to start.`,
    tip: "The line outside the 'first Starbucks' at Pike Place is for a photo, not for coffee — the roast is the same as every other Starbucks on Earth. Spend that half hour at any spot below.",
    places: [
      { name: "Espresso Vivace", blurb: "David Schomer's temple of espresso — his manuals trained a generation of American baristas. The sidewalk bar on Broadway is the classic experience.", address: "532 Broadway Ave E, Capitol Hill", coords: [47.6234, -122.3210], price: "$4–6" },
      { name: "Monorail Espresso", blurb: "A walk-up window in a downtown wall, slinging serious shots since 1980 — it began as Seattle's original espresso cart. No seats, no ceremony.", address: "510 Pike St, Downtown", coords: [47.6106, -122.3349], price: "$4–5" },
      { name: "Victrola Coffee Roasters", blurb: "Capitol Hill's living-room roastery on Pike. Single-origin pour-overs, roasting in view, and the least hurried tables in the neighborhood.", address: "310 E Pike St, Capitol Hill", coords: [47.6140, -122.3273], price: "$4–6" },
      { name: "Storyville Coffee", blurb: "Polished room above Pike Place with a straight view down to the market clock. The tourist-adjacent choice that locals quietly endorse.", address: "94 Pike St, Suite 34, Pike Place", coords: [47.6089, -122.3401], price: "$5–7" },
    ],
  },
  {
    slug: "seafood",
    cat: "SEAFOOD",
    name: "Oysters, salmon, chowder",
    teaser: "Happy-hour oysters, standing-room chowder, and the omakase worth booking a month out.",
    metaDesc: "Seattle seafood field guide: The Walrus and the Carpenter, Taylor Shellfish, Pike Place Chowder, and Sushi Kashiba.",
    lede: `Cold, clean water makes serious shellfish. Seattle's seafood culture runs from paper-cup chowder to edomae omakase, and the whole spectrum is worth your time.`,
    tip: "Oyster happy hours (usually opening hour, often twilight too) are the local cheat code — the same Pacific Northwest oysters at half the evening price.",
    places: [
      { name: "The Walrus and the Carpenter", blurb: "The marble oyster bar that made Ballard a food destination. No reservations; be there before the 4 PM open or put your name down and brewery-hop.", address: "4743 Ballard Ave NW, Ballard", coords: [47.6656, -122.3820], price: "$$$" },
      { name: "Taylor Shellfish Oyster Bar", blurb: "The 130-year-old shellfish farm's own bar — the no-wait, no-drama way to eat the region's best oysters, geoduck included if you're brave.", address: "410 Occidental Ave S, Pioneer Square", coords: [47.6003, -122.3327], price: "$$" },
      { name: "Pike Place Chowder", blurb: "The smoked-salmon chowder is the move at the national-award-hoarding Post Alley shop. Order ahead online and skip the queue entirely.", address: "1530 Post Alley, Pike Place", coords: [47.6096, -122.3417], price: "$" },
      { name: "Sushi Kashiba", blurb: "Shiro Kashiba apprenticed under Jiro Ono in Tokyo, then spent fifty years defining Seattle sushi. Omakase at the counter is the city's great splurge.", address: "86 Pine St, Pike Place", coords: [47.6100, -122.3408], price: "$$$$" },
    ],
  },
  {
    slug: "teriyaki",
    cat: "TERIYAKI",
    name: "Teriyaki: the true street food",
    teaser: "Invented here in 1976. Every strip mall has one, most are great, none are fancy — this is the city's actual signature dish.",
    metaDesc: "Seattle teriyaki explained: the 1976 origin story, why it's the city's real signature dish, and where to eat it.",
    lede: `In 1976, Toshihiro Kasahara opened a 500-square-foot shop and started grilling marinated chicken over rice for lunch crowds. Within a decade 'teriyaki' meant something in Seattle that it means nowhere else in America.`,
    tip: "Ordering protocol: chicken teriyaki, extra sauce, and don't overthink the venue — the divier the strip mall, the better the odds. Anything over $15 is suspicious.",
    places: [
      { name: "Toshi's Teriyaki Grill", blurb: "The founder himself, still grilling north of the city in Mill Creek. A pilgrimage for completists; the plate that started all of it.", address: "16505 Bothell Everett Hwy, Mill Creek", coords: [47.8564, -122.2188], price: "$12" },
      { name: "Grillbird Teriyaki", blurb: "The new-school torchbearer in West Seattle — same humble format, obsessive technique, and a char that justifies the neighborhood detour.", address: "4459 California Ave SW, West Seattle", coords: [47.5636, -122.3870], price: "$14" },
      { name: "Your nearest 4½-star strip-mall spot", blurb: "Genuinely: open the map, find the closest teriyaki joint with a hand-lettered sign and a line of regulars at noon. That's the authentic experience.", address: "Everywhere in Seattle", coords: null, price: "$12" },
    ],
  },
  {
    slug: "pho-and-dim-sum",
    cat: "PHO & DIM SUM",
    name: "Pho & dim sum",
    teaser: "Rainy day? Pho in Little Saigon fixes everything. Weekend morning? Follow the carts. The fogged-up windows never lie.",
    metaDesc: "Where to eat pho and dim sum in Seattle's Chinatown-International District and Little Saigon: Pho Bac, Jade Garden, Dough Zone.",
    lede: `The C-ID and Little Saigon hold the city's most reliable comfort food. The rule of thumb across both cuisines: follow the fogged-up windows and the full tables of regulars.`,
    tip: "Dim sum is a morning-to-early-afternoon event — carts thin out after 2 PM. Pho, meanwhile, is an all-day right, and never better than mid-downpour.",
    places: [
      { name: "Phở Bắc Súp Shop", blurb: "The family that brought pho to Seattle in 1982, now in the boat-shaped red landmark on Jackson. Deep broth, no gimmicks, occasional line, worth it.", address: "1240 S Jackson St, Little Saigon", coords: [47.5993, -122.3148], price: "$" },
      { name: "Jade Garden", blurb: "Cart-service dim sum with weekend crowds to match. Har gow, siu mai, sticky rice in lotus leaf — flag down everything that steams.", address: "424 7th Ave S, C-ID", coords: [47.5989, -122.3238], price: "$$" },
      { name: "Dough Zone", blurb: "The homegrown dumpling chain that out-executes most competitors nationally — xiao long bao, jian buns, dan dan noodles, minimal wait engineering.", address: "504 5th Ave S, C-ID", coords: [47.5977, -122.3273], price: "$$" },
    ],
  },
  {
    slug: "pastry",
    cat: "PASTRY",
    name: "The croissant wars",
    teaser: "Seattle takes lamination seriously. Arrive early — the good stuff sells out by 10.",
    metaDesc: "Seattle's best bakeries and croissants: Bakery Nouveau, Sea Wolf Bakers, Temple Pastries, Le Panier.",
    lede: `Some cities argue about pizza. Seattle argues about lamination. The bakery bench here is genuinely deep, and the only losing move is sleeping in.`,
    tip: "Weekend protocol: bakery first, everything else after. The marquee items at all four of these are routinely gone by mid-morning.",
    places: [
      { name: "Bakery Nouveau", blurb: "World-champion baker William Leaman's flagship. The twice-baked almond croissant is the single most-cited pastry in the city.", address: "4737 California Ave SW, West Seattle", coords: [47.5609, -122.3868], price: "$5–8" },
      { name: "Sea Wolf Bakers", blurb: "Brothers-run bread church by the canal in Fremont — the crusty loaves supply half the city's good restaurants, and the morning buns reward early arrival.", address: "3621 Stone Way N, Fremont", coords: [47.6519, -122.3417], price: "$4–7" },
      { name: "Temple Pastries", blurb: "The Central District's cult croissant house — expect the ornate, the seasonal, and a line of people who set alarms for it.", address: "2524 S Jackson St, Central District", coords: [47.5995, -122.2999], price: "$5–9" },
      { name: "Le Panier", blurb: "The Pike Place French institution since 1983. Not the trendiest — just reliably correct baguettes and croissants forty feet from the fish throwers.", address: "1902 Pike Pl, Pike Place", coords: [47.6100, -122.3424], price: "$3–6" },
    ],
  },
  {
    slug: "cocktails",
    cat: "NIGHTCAP",
    name: "Cocktails behind unmarked doors",
    teaser: "A speakeasy in a Belltown alley, a whiskey list the size of a novella, and the bar where Seattle bartending grew up.",
    metaDesc: "Seattle cocktail bars worth seeking out: Canon, Bathtub Gin & Co, and Zig Zag Café.",
    lede: `Seattle drinks in small, dim, obsessive rooms. Three of the best require either finding an unmarked door or trusting a stairway — all three reward it.`,
    tip: "These rooms are small and Seattle nights start early — arriving at opening (usually 5–6 PM) gets you seats that 9 PM arrivals wait an hour for.",
    places: [
      { name: "Canon", blurb: "'Whiskey and bitters emporium' undersells it: one of the largest spirits collections in the hemisphere and a cocktail program with national hardware.", address: "928 12th Ave, Capitol Hill", coords: [47.6114, -122.3168], price: "$16–18" },
      { name: "Bathtub Gin & Co", blurb: "Down an alley, behind an unmarked door in Belltown — a genuine two-story speakeasy pouring gin-forward classics in a former boiler room.", address: "2205 2nd Ave, Belltown", coords: [47.6135, -122.3450], price: "$15–17" },
      { name: "Zig Zag Café", blurb: "The hillclimb bar beside Pike Place where modern Seattle bartending was more or less invented. Ask for whatever the bartender feels like making.", address: "1501 Western Ave, Pike Place hillclimb", coords: [47.6083, -122.3425], price: "$15–17" },
    ],
  },
];

const dayTrips = [
  {
    slug: "mount-rainier",
    name: "Mount Rainier National Park",
    shortName: "Mount Rainier",
    meta: ["2.5 HR DRIVE", "FULL DAY"],
    teaser: "The mountain that photobombs the skyline, up close. Paradise wildflower meadows, glacier views, and pie on the way home.",
    metaDesc: "Mount Rainier day trip from Seattle: Paradise and the Skyline Trail, timed-entry reservations, what to pack, and the pie stop on the way home.",
    lede: `That white apparition floating over the skyline is a 14,411-foot glaciated volcano, and it is entirely reasonable to stand on its flank by 10 AM. Paradise — the aptly named south-side meadows — is the day trip against which all others are measured.`,
    stats: [
      ["DRIVE", "~2.5 hrs to Paradise via Ashford"],
      ["SEASON", "Meadows peak late Jul–Aug; road open year-round"],
      ["COST", "$30/vehicle + timed entry in summer"],
      ["ALTITUDE", "Paradise sits at 5,400 ft — pack layers"],
    ],
    plan: [
      { time: "7:00", title: "Leave Seattle early", text: "Beat the gate line. Last real coffee and gas are in Eatonville or Ashford — there's neither inside the park." },
      { time: "9:30", title: "Paradise & the Skyline Trail", text: "The full loop is 5.5 miles and earns every view: wildflower meadows, marmots, and the Nisqually Glacier groaning in the distance. Short on legs? Nisqually Vista is a gentle 1.2-mile version." },
      { time: "14:00", title: "Reflection Lakes & Narada Falls", text: "Two pull-offs on the drive down that deliver absurd returns per minute — Rainier mirrored in still water, and a 168-foot waterfall a two-minute walk from the road." },
      { time: "16:30", title: "Copper Creek Inn", text: "Just outside the gate in Ashford. Blackberry pie is the closing argument of this itinerary. Non-negotiable." },
    ],
    needToKnow: [
      "Summer requires a timed-entry reservation for the Paradise corridor in addition to the park fee — book on recreation.gov before you drive.",
      "Snow lingers at Paradise into July; trails can be icy when Seattle is sunny. Check conditions and bring real shoes.",
      "Cell service dies at the park boundary. Download offline maps before Ashford.",
      "Clear-day rule: if the Mountain is out in Seattle, it's spectacular up close. If it's socked in, consider Snoqualmie Falls instead — Paradise in a cloud is a very cold gray room.",
    ],
    map: { center: [46.8523, -121.7603], zoom: 9 },
    markers: [
      { name: "Paradise (Henry M. Jackson Visitor Center)", address: "Paradise Rd E, Mount Rainier NP", coords: [46.7861, -121.7368] },
      { name: "Nisqually Entrance", address: "SR 706, Ashford", coords: [46.7409, -121.9166] },
      { name: "Narada Falls", address: "Paradise Rd E", coords: [46.7752, -121.7469] },
      { name: "Copper Creek Inn", address: "35707 SR 706 E, Ashford", coords: [46.7541, -122.0308] },
    ],
    directions: "Paradise, Mount Rainier National Park",
  },
  {
    slug: "bainbridge-island",
    name: "Bainbridge Island",
    shortName: "Bainbridge",
    meta: ["35 MIN FERRY", "HALF DAY"],
    teaser: "Walk on the ferry from downtown — the crossing IS the attraction. Bookstores, bakeries, and a golden-hour sail home into the skyline.",
    metaDesc: "Bainbridge Island day trip from Seattle: walk-on ferry from Colman Dock, Winslow's bookstores and bakeries, and timing the golden-hour return crossing.",
    lede: `The lowest-effort, highest-reward trip in the region: walk onto a ferry downtown, spend 35 minutes on deck with the skyline and the Olympics trading places, and step off into a walkable waterfront town.`,
    stats: [
      ["FERRY", "35 min from Colman Dock, Pier 52"],
      ["FARE", "~$10 round trip, walk-on (collected westbound only)"],
      ["CAR NEEDED", "No — Winslow is entirely walkable"],
      ["TIMING", "Sailings roughly hourly; check WSDOT"],
    ],
    plan: [
      { time: "10:00", title: "Walk on at Colman Dock", text: "Pier 52, downtown. No reservation needed for walk-ons — tap an ORCA card or buy at the terminal, then head straight for the bow deck." },
      { time: "10:35", title: "The crossing", text: "Skyline behind, Olympics ahead, occasionally a porpoise escort. Cold on deck year-round; that's what the coffee is for." },
      { time: "11:15", title: "Winslow Way", text: "The main street starts five minutes from the dock: Eagle Harbor Book Co. for browsing, Blackbird Bakery for the pastry case, galleries and tasting rooms in between. The Bainbridge Island Museum of Art at the top of the street is free and excellent." },
      { time: "14:00", title: "Mora Iced Creamery, then the shoreline", text: "Island-made ice cream, then the Waterfront Trail loop past the harbor before catching a boat back." },
      { time: "16:30", title: "Sail home at golden hour", text: "The eastbound evening crossing, with the sun low behind you and the skyline lighting up ahead, is the single best free show in Seattle tourism." },
    ],
    needToKnow: [
      "Walk on. Vehicle queues can run hours on summer weekends; foot passengers stroll aboard until minutes before sailing.",
      "Fares are collected westbound only — the return ride is 'free.'",
      "Check the WSDOT ferries schedule the morning of; sailings occasionally cancel for crewing.",
      "Garden people: Bloedel Reserve, a 150-acre landscape masterpiece, is 15 minutes north by bus or taxi — book timed entry ahead.",
    ],
    map: { center: [47.6180, -122.4500], zoom: 12 },
    markers: [
      { name: "Colman Dock (Pier 52)", address: "801 Alaskan Way, Seattle", coords: [47.6023, -122.3389] },
      { name: "Bainbridge Ferry Terminal", address: "270 Olympic Dr SE, Bainbridge Island", coords: [47.6229, -122.5100] },
      { name: "Winslow Way (main street)", address: "Winslow Way E, Bainbridge Island", coords: [47.6262, -122.5215] },
      { name: "Bainbridge Island Museum of Art", address: "550 Winslow Way E", coords: [47.6252, -122.5170] },
    ],
    directions: "Bainbridge Island Ferry Terminal, Seattle WA",
    ferryLink: true,
  },
  {
    slug: "snoqualmie-falls",
    name: "Snoqualmie Falls",
    shortName: "Snoqualmie",
    meta: ["40 MIN DRIVE", "2–3 HOURS"],
    teaser: "A 268-foot curtain of water — taller than Niagara — twenty-five minutes from downtown. Twin Peaks fans, this is that lodge.",
    metaDesc: "Snoqualmie Falls day trip from Seattle: the overlook, the lower falls trail, Twin Peaks landmarks, and pairing it with the Rattlesnake Ledge hike.",
    lede: `The shortest trip on this list and the best effort-to-awe ratio in the region: a 268-foot waterfall — a hundred feet taller than Niagara — thundering into a basalt bowl less than an hour from your hotel.`,
    stats: [
      ["DRIVE", "~40 min east on I-90"],
      ["COST", "Free; paid parking lot at the falls"],
      ["EFFORT", "Overlook: none. Lower falls: 1.4 mi round trip"],
      ["PEAK FLOW", "After heavy rain and spring melt"],
    ],
    plan: [
      { time: "9:00", title: "The overlook", text: "Two minutes from the parking lot to the railing. After a wet week the mist climbs all the way up to meet you — bring the rain shell you were told to pack." },
      { time: "9:45", title: "Lower falls trail", text: "A 1.4-mile round-trip switchback to the riverbank, where the falls stop being scenery and become weather. The boardwalk viewpoint at the bottom is the shot." },
      { time: "11:00", title: "Salish Lodge, if you please", text: "The lodge perched on the falls' lip is Twin Peaks' Great Northern Hotel, exterior-wise. Brunch is famous and priced accordingly." },
      { time: "12:00", title: "Extend it", text: "Twenty minutes further: Twede's Café in North Bend — the RR Diner itself — for cherry pie and 'a damn fine cup of coffee,' or the Rattlesnake Ledge hike (4 mi round trip) if you'd rather earn the pie first." },
    ],
    needToKnow: [
      "The falls are free and open year-round; the main lot fills by mid-morning on weekends.",
      "Peak drama is October–May when the river runs high. Late-summer flow is thinner — still lovely, less thunderous.",
      "Rattlesnake Ledge is deservedly popular: arrive before 9 AM on weekends or embrace the conga line.",
    ],
    map: { center: [47.5100, -121.8100], zoom: 11 },
    markers: [
      { name: "Snoqualmie Falls Overlook", address: "6501 Railroad Ave SE, Snoqualmie", coords: [47.5417, -121.8377] },
      { name: "Twede's Café", address: "137 W North Bend Way, North Bend", coords: [47.4957, -121.7868] },
      { name: "Rattlesnake Ledge Trailhead", address: "17905 Cedar Falls Rd SE, North Bend", coords: [47.4344, -121.7690] },
    ],
    directions: "Snoqualmie Falls, Snoqualmie WA",
  },
  {
    slug: "leavenworth",
    name: "Leavenworth",
    shortName: "Leavenworth",
    meta: ["2 HR DRIVE", "FULL DAY"],
    teaser: "A Bavarian village in the Cascades, committed to the bit since 1962. Bratwurst, beer halls, river floats, and a magical lights season.",
    metaDesc: "Leavenworth day trip from Seattle: the Bavarian village drive over Stevens Pass, beer halls, summer river floats, and the winter Christmas-lights season.",
    lede: `In 1962, a dying timber town bet everything on becoming a Bavarian village — architecture codes, lederhosen, the works. Sixty years on, the bit is the town, the Alps-adjacent scenery holds up its end, and the bratwurst is legitimately good.`,
    stats: [
      ["DRIVE", "2–2.5 hrs via US-2 over Stevens Pass"],
      ["SEASON", "Great year-round; December is peak (and packed)"],
      ["SUMMER MOVE", "Float the Wenatchee River"],
      ["WINTER NOTE", "Carry chains over the pass"],
    ],
    plan: [
      { time: "8:00", title: "Drive US-2", text: "The Stevens Pass route is the scenic argument: Skykomish River, granite walls, and Deception Falls a two-minute leg-stretch off the highway." },
      { time: "10:30", title: "Front Street", text: "The full Bavarian streetscape. München Haus for brats and a liter on the biergarten deck; the Gingerbread Factory for the kitsch course." },
      { time: "13:00", title: "Pick your afternoon", text: "Summer: float the Wenatchee River or walk the Icicle Gorge loop. Shoulder season: wine tasting rooms line the village. Connoisseurs of the absurd: the Nutcracker Museum has over 7,000 of them." },
      { time: "17:00", title: "Dinner and the drive home", text: "Or stay for the lights — from Thanksgiving through February the village glows nightly, and it is genuinely, unironically magical." },
    ],
    needToKnow: [
      "December weekends are mobbed — hotels book out months ahead and Front Street becomes a slow shuffle. Go midweek for lights with elbow room.",
      "Loop option: go out via US-2, return via Blewett Pass and I-90 to make it a circle drive.",
      "Winter travel over Stevens Pass can require chains — check WSDOT pass reports before leaving.",
    ],
    map: { center: [47.6300, -121.1000], zoom: 9 },
    markers: [
      { name: "Front Street (village center)", address: "Front St, Leavenworth", coords: [47.5962, -120.6615] },
      { name: "Deception Falls", address: "US-2, Skykomish", coords: [47.7147, -121.1955] },
    ],
    directions: "Leavenworth, WA",
  },
  {
    slug: "san-juan-islands",
    name: "San Juan Islands",
    shortName: "San Juans",
    meta: ["3–4 HR + FERRY", "LONG DAY / OVERNIGHT"],
    teaser: "Orcas in the wild, lavender farms, and harbor towns on island time. Doable in a long day; better as an overnight.",
    metaDesc: "San Juan Islands trip from Seattle: Anacortes ferry logistics, Friday Harbor, Lime Kiln Point orca watching, and why to stay overnight.",
    lede: `An archipelago where the resident orcas outrank everyone, the pace drops to island time the moment you drive aboard, and the hardest decision of the day is lavender farm versus alpaca farm. The one trip on this list that truly argues for an overnight.`,
    stats: [
      ["GETTING THERE", "90 min to Anacortes + ~1 hr ferry"],
      ["ORCA SEASON", "Most reliable May–September"],
      ["BEST SHORE VIEWING", "Lime Kiln Point State Park"],
      ["RESERVATIONS", "Essential for vehicles"],
    ],
    plan: [
      { time: "6:30", title: "Drive to Anacortes", text: "Ninety minutes north. Vehicle reservations (Save A Spot, WSDOT) are close to mandatory in summer — walk-ons are always flexible if you'd rather rent wheels on-island." },
      { time: "8:30", title: "Ferry to Friday Harbor", text: "About an hour threading the archipelago — arguably the prettiest ferry run in the Lower 48. Deck seats, obviously." },
      { time: "10:00", title: "Friday Harbor", text: "Compact, walkable harbor town: the Whale Museum to calibrate your orca knowledge, then coffee on the docks." },
      { time: "12:00", title: "Lime Kiln Point", text: "'Whale Watch Park' — the best shore-based orca viewing in the world. Summer afternoons with the lighthouse in frame and a picnic is the platonic San Juans experience." },
      { time: "15:00", title: "Farms and roadside stands", text: "Pelindaba Lavender's purple fields, San Juan Vineyard, honesty-box farm stands. Then the 17:30-ish boat — or, wisely, your inn." },
    ],
    needToKnow: [
      "Do the math honestly: it's a 15+ hour round trip as a day trip. An overnight on San Juan or Orcas Island transforms it.",
      "Orcas Island option: Moran State Park and the Mount Constitution summit road — the best viewpoint in the entire archipelago.",
      "Whale-watching boats run from Friday Harbor if you want guaranteed proximity; shore viewing at Lime Kiln is free and ethically unbeatable.",
      "Summer vehicle ferries sell out. Reserve the moment plans firm up, or go as a walk-on and rent a bike or moped in Friday Harbor.",
    ],
    map: { center: [48.5500, -123.0200], zoom: 10 },
    markers: [
      { name: "Anacortes Ferry Terminal", address: "2100 Ferry Terminal Rd, Anacortes", coords: [48.5065, -122.6790] },
      { name: "Friday Harbor", address: "Friday Harbor, San Juan Island", coords: [48.5348, -123.0158] },
      { name: "Lime Kiln Point State Park", address: "1567 Westside Rd, Friday Harbor", coords: [48.5160, -123.1520] },
      { name: "Pelindaba Lavender Farm", address: "45 Hawthorne Ln, Friday Harbor", coords: [48.5000, -123.0680] },
    ],
    directions: "Anacortes Ferry Terminal, Anacortes WA",
    ferryLink: true,
  },
  {
    slug: "olympic-peninsula",
    name: "Olympic Peninsula",
    shortName: "Olympics",
    meta: ["FERRY + 2 HR", "FULL DAY MINIMUM"],
    teaser: "Three worlds in one park: mile-high ridge views, a mossy rainforest cathedral, and wild Pacific beaches. Pick one per day.",
    metaDesc: "Olympic National Park from Seattle: choosing between Hurricane Ridge, the Hoh Rainforest, and Rialto Beach, with ferry and drive logistics.",
    lede: `Olympic National Park is nearly a million acres holding three separate ecosystems — alpine ridgeline, temperate rainforest, and wilderness coast. The honest advice nobody puts on the brochure: it's bigger than Rhode Island. Pick ONE region per day.`,
    stats: [
      ["ACCESS", "Ferry to Bainbridge/Kingston, then drive"],
      ["COST", "$30/vehicle park entrance"],
      ["HURRICANE RIDGE", "~3 hrs door to door"],
      ["HOH RAINFOREST", "~4.5 hrs — consider overnighting"],
    ],
    plan: [
      { time: "OPTION A", title: "Hurricane Ridge", text: "The day-trippable one. Ferry to Bainbridge, drive to Port Angeles, then the 17-mile ridge road to mile-high meadows with the interior Olympics filling the horizon. Deer guaranteed; Canada visible." },
      { time: "OPTION B", title: "Hoh Rainforest", text: "Twelve feet of rain a year builds a cathedral: the Hall of Mosses (0.8 mi) among maples upholstered in green. Far — earns an overnight in Forks or Port Angeles." },
      { time: "OPTION C", title: "Rialto Beach", text: "Wilderness coast: black sand, drift logs like fallen towers, sea stacks offshore. Time it to low tide and walk 1.5 miles to the Hole-in-the-Wall arch." },
    ],
    needToKnow: [
      "One region per day. Attempting Ridge + Hoh + coast in a day means twelve hours of driving and zero joy.",
      "Check the Hurricane Ridge road status before going — it's weather-gated even in shoulder seasons.",
      "For Rialto's Hole-in-the-Wall, consult a tide table and walk out on a falling tide.",
      "The Edmonds–Kingston ferry is often the faster crossing northbound; either boat works.",
    ],
    map: { center: [47.9000, -123.8000], zoom: 8 },
    markers: [
      { name: "Hurricane Ridge Visitor Center", address: "Hurricane Ridge Rd, Port Angeles", coords: [47.9692, -123.4979] },
      { name: "Hoh Rainforest (Hall of Mosses)", address: "18113 Upper Hoh Rd, Forks", coords: [47.8607, -123.9348] },
      { name: "Rialto Beach", address: "Mora Rd, Forks", coords: [47.9204, -124.6390] },
      { name: "Port Angeles (base town)", address: "Port Angeles, WA", coords: [48.1181, -123.4307] },
    ],
    directions: "Hurricane Ridge Visitor Center, Port Angeles WA",
    ferryLink: true,
  },
];

const itineraries = [
  {
    slug: "24-hours",
    num: "01",
    name: "24 Hours in Seattle",
    shortName: "24 Hours",
    hours: "24 HOURS",
    meta: ["6 STOPS", "FIRST-TIMERS"],
    teaser: "Market before the crowds, the new waterfront, a C-ID lunch, Chihuly at dusk, and the postcard from Kerry Park.",
    metaDesc: "The perfect 24 hours in Seattle: Pike Place before the crowds, the Overlook Walk, a Chinatown-International District lunch, Chihuly Garden & Glass, Kerry Park at golden hour, and Capitol Hill for dinner.",
    lede: `One day, done right, hits the market, the water, two neighborhoods, and the single best view in the city — without ever feeling rushed if you start early.`,
    stats: [
      ["PACE", "Brisk — start by 7:30"],
      ["STOPS", "6, across 4 neighborhoods"],
      ["GET AROUND", "Walking + one light rail hop"],
      ["BEST FOR", "First-timers with one shot at the city"],
    ],
    plan: [
      { time: "7:30", title: "Pike Place, before the crowds", text: "Coffee at Storyville overlooking the market sign, watch the vendors set up, first salmon toss of the day." },
      { time: "10:00", title: "Overlook Walk → Waterfront", text: "Descend the new stair-park to Elliott Bay. Seattle Aquarium if you have kids; otherwise just breathe the salt air." },
      { time: "12:30", title: "Lunch in the C-ID", text: "Light rail two stops south. Pho, BBQ pork over rice, or hand-pulled noodles. Snack run through Uwajimaya after." },
      { time: "15:00", title: "Seattle Center", text: "Space Needle or — hot take — skip it and do Chihuly Garden & Glass instead. The glasshouse at dusk is unreal." },
      { time: "18:00", title: "Kerry Park golden hour", text: "Ten-minute climb up Queen Anne. The photo you came for: Needle, skyline, Rainier if she's out." },
      { time: "20:00", title: "Dinner + nightcap, Capitol Hill", text: "Walk-ins at the bar are the local move. End at Canon or a dive on Pike/Pine, depending on your constitution." },
    ],
    needToKnow: [
      "Book Chihuly Garden & Glass tickets online — the timed-entry queue in person can eat 30 minutes you don't have.",
      "Kerry Park has maybe a dozen parking spots and no lot; arrive 20 minutes before sunset or plan to circle.",
      "The C-ID hop is one Link light rail stop from Westlake or two from Pioneer Square — tap your ORCA card, don't drive.",
    ],
    map: { center: [47.614, -122.338], zoom: 12 },
    markers: [
      { name: "Storyville Coffee", address: "94 Pike St, Suite 34", coords: [47.6089, -122.3401] },
      { name: "Overlook Walk", address: "Pike St & Western Ave", coords: [47.6081, -122.3432] },
      { name: "Uwajimaya", address: "600 5th Ave S", coords: [47.5975, -122.3282] },
      { name: "Chihuly Garden & Glass", address: "305 Harrison St", coords: [47.6214, -122.3493] },
      { name: "Kerry Park", address: "211 W Highland Dr", coords: [47.6295, -122.3599] },
      { name: "Capitol Hill (Pike/Pine)", address: "Pike St & 11th Ave", coords: [47.6142, -122.321] },
    ],
  },
  {
    slug: "48-hours",
    num: "02",
    name: "48 Hours in Seattle",
    shortName: "48 Hours",
    hours: "48 HOURS",
    meta: ["5 STOPS", "NEIGHBORHOOD HOPPERS"],
    teaser: "Add a second day: the Ballard Locks, a neighborhood crawl, Fremont's weirdness, and Alki at sunset via water taxi.",
    metaDesc: "Seattle in 48 hours: the day-two plan after the 24-hour itinerary — Ballard Locks and fish ladder, Ballard Ave, Fremont's troll and rocket, a water taxi to Alki Beach, and live music at night.",
    lede: `Day two is the neighborhood-hopping day — north to the boats and salmon at the Locks, over to Fremont's committed weirdness, then a water taxi across the bay for sunset on Alki. Pairs with the 24-hour plan as the front half.`,
    stats: [
      ["PACE", "Moderate — day 2 of a 2-day trip"],
      ["STOPS", "5, across 3 neighborhoods"],
      ["GET AROUND", "Walking + a short water taxi crossing"],
      ["BEST FOR", "Visitors adding a second full day"],
    ],
    plan: [
      { time: "9:00", title: "Ballard Locks & the fish ladder", text: "Boats going up, salmon going upstream, herons supervising. Free and genuinely mesmerizing." },
      { time: "11:30", title: "Ballard Ave crawl", text: "Sunday? Farmers market. Any day: record shops, Nordic Museum, then oysters at Walrus when doors open at 4 — or brewery-hop until then." },
      { time: "14:30", title: "Fremont weirdness tour", text: "Troll → rocket → Lenin → canal path. Gasworks Park for the skyline-over-kites panorama." },
      { time: "17:30", title: "Water taxi to West Seattle", text: "Five minutes across the bay, skyline glowing behind you. Fish and chips on Alki as the sun drops behind the Olympics." },
      { time: "21:00", title: "Live music", text: "Check the Crocodile, Neumos, or Tractor Tavern. This city exported grunge; the venues still deliver." },
    ],
    needToKnow: [
      "The West Seattle Water Taxi runs on a seasonal schedule (daily roughly April–October, weekdays-only in winter) — check King County Metro's schedule before you plan the crossing.",
      "Ballard Ave is closed to cars for the Sunday farmers market (year-round, 10 AM–3 PM) — a plus for walking, a headache if you drove.",
      "Book one live-music ticket ahead if there's a touring act; the walk-in door price is a gamble on a Friday.",
    ],
    map: { center: [47.645, -122.375], zoom: 12 },
    markers: [
      { name: "Ballard Locks", address: "3015 NW 54th St", coords: [47.665, -122.3966] },
      { name: "Ballard Ave", address: "Ballard Ave NW", coords: [47.6683, -122.3835] },
      { name: "Fremont Troll", address: "N 36th St & Aurora Ave N", coords: [47.651, -122.3496] },
      { name: "West Seattle Water Taxi (Seacrest dock)", address: "1660 Harbor Ave SW", coords: [47.5837, -122.4098] },
      { name: "Tractor Tavern", address: "5213 Ballard Ave NW", coords: [47.6669, -122.3839] },
    ],
  },
  {
    slug: "72-hours",
    num: "03",
    name: "72 Hours in Seattle",
    shortName: "72 Hours",
    hours: "72 HOURS",
    meta: ["6 STOPS", "EXTENDED STAYS"],
    teaser: "Day three branches: a day trip into the mountains, or the unhurried city day — parks, books, art, and a farewell dinner worth booking ahead.",
    metaDesc: "Seattle in 72 hours: the day-three plan after 48 hours in the city — choose a day trip to Mount Rainier or the San Juans, or the unhurried city day through Volunteer Park, SAM, and Georgetown, ending with a farewell dinner.",
    lede: `By day three you've earned a choice. Chase alpine drama on one of the day trips, or stay in the city for the unhurried version below — parks, bookstores, art, and one last dinner worth booking in advance. Follows the 48-hour plan.`,
    stats: [
      ["PACE", "Flexible — day 3, your call"],
      ["STOPS", "6 for the city-day route"],
      ["GET AROUND", "Walking + a short drive to Georgetown"],
      ["BEST FOR", "Extended stays with a day to spare"],
    ],
    plan: [
      { time: "8:00", title: "Choose your day trip — or don't", text: "Rainier for alpine drama, Bainbridge for the easy ferry loop, Snoqualmie Falls if you're short on time. Details on each Day Trips page. Skip this and sleep in for the city-day route below." },
      { time: "9:00", title: "Volunteer Park Conservatory", text: "A Victorian glasshouse of palms and cacti, usually near-empty on a weekday morning. The water tower next door has a free 360° view for the climb." },
      { time: "11:00", title: "Elliott Bay Book Company", text: "Capitol Hill's cathedral of a bookstore. Basement café for a coffee break, then browse until something follows you to the register." },
      { time: "13:00", title: "Seattle Art Museum (SAM)", text: "Downtown's big-ticket museum — Northwest Coast Native art and the rotating special exhibits are the draws. Closed Mondays." },
      { time: "15:00", title: "Georgetown art walk", text: "Seattle's least-polished, most genuine arts district. Galleries, dive bars, and pizza at Via Tribunali in a converted garage." },
      { time: "19:00", title: "Farewell dinner", text: "Book ahead once: The Walrus if you missed it, Sushi Kashiba, or Il Nido in a log cabin in West Seattle." },
    ],
    needToKnow: [
      "SAM is closed Mondays — swap in the Georgetown art walk earlier and push dinner up if your day three lands on one.",
      "Georgetown's biggest night is the second-Saturday Art Attack — check This Weekend before you plan around it, since it's monthly, not weekly.",
      "Whichever farewell dinner you pick, call or book online a day ahead — all three routinely sell out same-day tables.",
    ],
    map: { center: [47.598, -122.335], zoom: 12 },
    markers: [
      { name: "Volunteer Park Conservatory", address: "1400 E Galer St", coords: [47.6303, -122.3151] },
      { name: "Elliott Bay Book Company", address: "1521 10th Ave", coords: [47.6142, -122.3169] },
      { name: "Seattle Art Museum", address: "1300 1st Ave", coords: [47.6075, -122.3382] },
      { name: "Georgetown art walk", address: "Airport Way S, Georgetown", coords: [47.5551, -122.3286] },
      { name: "Il Nido", address: "4747 California Ave SW", coords: [47.5623, -122.3866] },
      { name: "Great Wheel (last look)", address: "1301 Alaskan Way", coords: [47.6076, -122.3428] },
    ],
  },
];

/* This-weekend dispatch — update weekly, then `node build.js`.
   Picks with passed dates trigger a stale banner automatically (page.js). */
const weekend = {
  updated: "July 11, 2026",
  label: "July 11–12, 2026",
  endDate: "2026-07-12", // last day of this weekend, ISO — drives the stale check
  picks: [
    { day: "SAT PM", title: "Georgetown Art Attack", text: "Second Saturday of the month means the whole Airport Way strip opens up — studios, galleries, pop-ups, live music, roughly 6–9 PM. Start at the Trailer Park Mall, end at Jules Maes Saloon.", link: { label: "Georgetown dossier", href: "/neighborhoods/georgetown/" } },
    { day: "SAT AM", title: "University District Farmers Market", text: "One of the city's oldest and biggest — 9 AM to 2 PM, year-round, on University Way. Peak summer produce right now; berries are the assignment." },
    { day: "SUN", title: "The market double-header", text: "Ballard Farmers Market in the morning, then the flat 25-minute canal walk to the Fremont Sunday Market. Two markets, one troll, zero driving.", link: { label: "Ballard dossier", href: "/neighborhoods/ballard/" } },
    { day: "ALL WKND", title: "Sockeye at the Locks", text: "July is peak salmon-ladder season at the Ballard Locks — the underwater viewing windows are as busy as they get all year. Free, open daily.", link: { label: "The Locks", href: "/neighborhoods/ballard/" } },
    { day: "GOLDEN HR", title: "Kerry Park at ~9:05 PM", text: "Mid-July sunsets land just after nine. Clear evening? Be on the Queen Anne overlook twenty minutes early with takeout.", link: { label: "Queen Anne dossier", href: "/neighborhoods/queen-anne-seattle-center/" } },
    { day: "IF CLEAR", title: "Rainier's meadows are waking up", text: "Paradise wildflowers typically start mid-July. If the Mountain is out, this is the weekend window opening — book the timed entry before you drive.", link: { label: "Rainier day trip", href: "/day-trips/mount-rainier/" } },
  ],
  seasonNote: "July is festival season — Seafair events, food festivals, and block parties rotate through the calendar, and their dates shift year to year. Check the organizers directly before building a day around one.",
  protocol: [
    { time: "SAT 8:00", title: "Bakery run", text: "Croissant economics are ruthless: the good stuff is gone by 10. Pick your bakery from the doctrine and go." },
    { time: "SAT 10:00", title: "A market or the Locks", text: "Saturday markets (U-District, Capitol Hill in season) or boats-and-salmon at the Ballard Locks." },
    { time: "SAT 14:00", title: "One dossier, done properly", text: "Pick a single neighborhood and give it the afternoon. Resist the urge to sample three." },
    { time: "SAT 20:00", title: "A show", text: "Check the Tractor, Neumos, and the Crocodile calendars. This city exported grunge; the rooms still deliver." },
    { time: "SUN 10:00", title: "Ballard → Fremont", text: "The Sunday market double-header, connected by the canal path. Lunch from whichever stall has the longest local line." },
    { time: "SUN 17:00", title: "Water taxi to Alki", text: "Fish and chips on the beach, skyline behind you, Olympics going pink across the Sound." },
    { time: "SUN 20:45", title: "Golden hour, Kerry Park", text: "End the weekend with the postcard. Free, always open, never gets old." },
  ],
};

/* trip card art — same SVGs as the homepage cards, reused on detail pages */
const tripArt = {
  "mount-rainier": `<svg class="trip-art" viewBox="0 0 300 160"><rect width="300" height="160" fill="#16273d"/><path d="M30 160 L150 30 L175 55 L200 35 L270 160 Z" fill="#4a5a74"/><path d="M150 30 L175 55 L200 35 L226 78 L188 66 L162 82 L128 62 Z" fill="#efe4da"/><circle cx="60" cy="42" r="14" fill="#e9c4ad" opacity="0.9"/><path d="M0 160 L60 120 L110 145 L160 118 L220 148 L300 125 L300 160 Z" fill="#0f1c2e"/></svg>`,
  "bainbridge-island": `<svg class="trip-art" viewBox="0 0 300 160"><rect width="300" height="160" fill="#16273d"/><path d="M0 100 Q75 80 150 100 T300 100 L300 160 L0 160 Z" fill="#1d3049"/><path d="M60 100 L140 100 L132 84 L68 84 Z" fill="#e8e4da"/><rect x="80" y="70" width="44" height="14" rx="3" fill="#2e7d5b"/><path d="M180 95 l14 -34 4 0 14 34" fill="#24384f"/><circle cx="250" cy="40" r="16" fill="#e9c4ad" opacity="0.8"/><path d="M0 70 L50 45 L100 68 L160 42 L230 66 L300 48 L300 78 L0 88 Z" fill="#12233a"/></svg>`,
  "snoqualmie-falls": `<svg class="trip-art" viewBox="0 0 300 160"><rect width="300" height="160" fill="#16273d"/><path d="M0 40 L90 40 L120 20 L190 20 L220 40 L300 40 L300 0 L0 0 Z" fill="#12233a"/><path d="M120 40 C118 80 122 110 112 150 M150 40 C152 85 146 115 156 150 M180 40 C178 78 184 112 176 150" stroke="#bcd4e6" stroke-width="10" fill="none" opacity="0.85"/><path d="M0 150 Q150 135 300 150 L300 160 L0 160 Z" fill="#0f1c2e"/><path d="M60 40 l10 -22 6 0 10 22" fill="#24384f"/></svg>`,
  "leavenworth": `<svg class="trip-art" viewBox="0 0 300 160"><rect width="300" height="160" fill="#16273d"/><path d="M0 120 Q40 90 80 115 Q90 100 110 112 L110 160 L0 160 Z" fill="#0f1c2e"/><path d="M300 120 Q260 88 215 116 L215 160 L300 160 Z" fill="#0f1c2e"/><path d="M110 160 L110 90 L125 74 L140 90 L140 160 M150 160 L150 82 L168 62 L186 82 L186 160 M196 160 L196 92 L208 80 L220 92 L220 160" fill="#24384f"/><path d="M118 92 h14 M158 84 h20 M200 96 h12" stroke="#ffd9a0" stroke-width="4"/><circle cx="52" cy="40" r="13" fill="#e9c4ad" opacity="0.8"/></svg>`,
  "san-juan-islands": `<svg class="trip-art" viewBox="0 0 300 160"><rect width="300" height="160" fill="#16273d"/><path d="M0 110 Q75 95 150 110 T300 110 L300 160 L0 160 Z" fill="#1d3049"/><path d="M40 110 Q70 84 105 102 Z M170 108 Q205 78 250 100 Z" fill="#12233a"/><path d="M140 96 q10 -14 22 0 q-4 -22 8 -30" stroke="#8fb8a8" stroke-width="5" fill="none"/><circle cx="240" cy="36" r="14" fill="#e9c4ad" opacity="0.85"/><path d="M60 120 q12 8 24 0 M180 126 q12 8 24 0" stroke="#3d5a7a" stroke-width="3" fill="none"/></svg>`,
  "olympic-peninsula": `<svg class="trip-art" viewBox="0 0 300 160"><rect width="300" height="160" fill="#16273d"/><path d="M0 160 L70 60 L100 90 L140 50 L180 95 L230 45 L300 160 Z" fill="#31435e"/><path d="M140 50 L158 72 L128 68 Z M230 45 L250 72 L214 66 Z" fill="#efe4da"/><path d="M20 160 l14 -30 4 0 14 30 M60 160 l16 -36 4 0 16 36 M250 160 l14 -28 4 0 14 28" fill="#0f2438"/><path d="M0 150 Q150 138 300 150 L300 160 L0 160 Z" fill="#0d1a2b"/></svg>`,
};

module.exports = { neighborhoods, eatCategories, dayTrips, itineraries, tripArt, weekend };
